Avoid NPE from Canavs
ArtOfIllusion/ArtOfIllusion pull request #267
Opened 2022-01-29 19:46 UTC by makiam

Clicking on ObjectPreview canvas inside Tools dialogs trows NPE into log because of no animator set for this views

2022-02-02 03:34 UTC, Sailsman63 commented
What exact conditions does this affect? I've never seen this, and don't know how to duplicate the issue.

2022-02-02 07:43 UTC, makiam commented
See this exception from Tools previews, where Canvas placed inside dialogs but Amimator is not attached to it.
So to see this just open ex CSG tool dialog and click on preview. Exception is thrown into console.

2022-02-02 16:47 UTC, peteihis commented
What do you mean by "CSG tool dialog"? 

- The "boolean" tool in the Tools menu uses "CSGDialog", which uses "ObjectPreviewCanvas" which extends "ViewerCanvas" and nowhere it sets an animation engine an nowhere calls one either.
- The "CSGEditorWindow" extends "ObjectEditorWindow" which sets a new animation engine to each of the four windows it creates.

Anyway there is nothing wrong with ViewerCanvas. If there is a call to a part of it that has not been set in the first place then it _should_ show up as an error or exception. If some extension of ViewerCanvas has a call to an animation engine that is not present, then the correct fix would be to add the missing engine or to drop the failing call.

2022-02-02 16:48 UTC, peteihis commented
And I could not reproduce the problem at least with the Boolean dialog.

2022-02-02 17:10 UTC, peteihis commented
Ookay.... Sorry!

Forget what I just wrote, this thing is happening! What it takes is to center click on the viewer of an ObjectPreviewCanvas. 

OPC does not set an animation engine as there is nothing to animate, but it doe use RotateViewTool, which registers mouse up with no drag vector as the centering command. 

But I dont't think the correction should be done in ViewerCanvas to ignore the call. Rather the mouseRelesed of OPC should be rewritten to ignore the "empty center click". -- Unless we want to add an animation engine to the object previews?

2022-02-02 20:32 UTC, peteihis commented
> But I dont't think the correction should be done in ViewerCanvas to ignore the call.

And thinking again this fix **makiam** is suggesting might be the best or at least simplest way to handle it after all. Every time there is a `mousePressed` there needs to be a `mouseReleased`. Otherwise the ViewerCanvas will stay in dragging mode, thinking that the mouse is still being pressed.

In  `ObjectPreviewCanvas` the fix should look like this (tested):

~~~~Java
  private Point mousePressedPoint;
  ....

  @Override
  protected void mousePressed(WidgetMouseEvent e)
  {
    mousePressedPoint = e.getPoint();
    ....
 
  @Override
  protected void mouseReleased(WidgetMouseEvent e)
  {
    if (activeTool != metaTool || ! e.getPoint().equals(mousePressedPoint))
      activeTool.mouseReleased(e, this);
    else
    {
      mouseDown = false;
      rotating  = false;
    }
  }
~~~~

Then again, the idea was thrown in the air already before that the preview canvases could take a face lift...

2022-02-02 22:16 UTC, Sailsman63 commented
Okay, got this duplicated. I think that we should probably do this for now as a quick-fix.

2022-02-02 22:17 UTC, Sailsman63 requested changes

2022-02-02 22:17 UTC, Sailsman63 commented on ArtOfIllusion/src/artofillusion/ViewerCanvas.java
> +    if(null != animation) animation.start(coords, pointInSpace, scale, orientation, navigation);
Condition order is backwards here. For readability, it should be `if(animation != null)`

2022-02-07 21:29 UTC, Sailsman63 approved these changes

2022-02-07 21:29 UTC, Sailsman63 commented
Thanks!

2022-02-07 21:30 UTC, merged