Catch for NoClasDefFoundError
ArtOfIllusion/ArtOfIllusion pull request #78
Opened 2018-01-06 19:15 UTC by makiam

I try to install GLRenderer plugin with SPManager. 
Once application is restarted it stuck on showing TitleWindow.
I see NoClassDefFoundError as this plugin expected classes from old JOGL

2018-01-19 05:31 UTC, Sailsman63 commented
Not sure why this error is being thrown, rather than `ClassNotfoundException`

Perhaps our load routine needs a little work. I think this is probably a little to targeted as a fix. Next time you find something like this, please file it as a bug report.

2018-04-04 02:10 UTC, Sailsman63 commented
@peastman how would you feel about catching all (`LinkageError`s)[https://docs.oracle.com/javase/7/docs/api/java/lang/LinkageError.html] here, just to insulate ourselves from any sort of oops that the plugin code generates?

I'd also like to see the Plugin repo updated to mark the current version of `GLRenderer` as incompatible with 3.0.3 and up, as there is a certain type of user that always starts every new install with 'doonload all teh pluginz'

2018-04-04 17:26 UTC, peastman commented
That sounds reasonable.  I wonder if we should just catch `Error`?  Even if it's something really strange that leaves the JVM in a broken state, we might at least be able to display a message telling the user which plugin is causing the problem.

2021-11-11 20:10 UTC, Sailsman63 commented on ArtOfIllusion/src/artofillusion/PluginRegistry.java
> +    catch(NoClassDefFoundError ncdfe)
As previously mentioned, I think we do need to broaden this, at least to `LinkageError` if not all the way to just `Error`.

2021-11-11 20:11 UTC, Sailsman63 requested changes

2021-11-11 20:11 UTC, Sailsman63 commented on ArtOfIllusion/src/artofillusion/PluginRegistry.java
> +      new BStandardDialog("", UIUtilities.breakString(Translate.text("pluginLoadError", jar.file.getName())), BStandardDialog.ERROR).showMessageDialog(null);
As previously mentioned, I think we do need to broaden this, at least to `LinkageError` if not all the way to just `Error`.

2021-11-14 18:12 UTC, Sailsman63 commented on ArtOfIllusion/src/artofillusion/PluginRegistry.java
> +      new BStandardDialog("", UIUtilities.breakString(Translate.text("pluginLoadError", jar.file.getName())), BStandardDialog.ERROR).showMessageDialog(null);
Thanks for the update. I did some further testing with an (easy to make) broken plugin. We do need to just broaden all the way to `Error` here.

I can make the change myself, if you prefer.

2021-11-17 06:51 UTC, Sailsman63 approved these changes

2021-11-17 06:52 UTC, Sailsman63 commented
Thank you!

2021-11-17 06:52 UTC, merged